[versions]
agp = "9.3.1"
kotlin = "2.4.10"

android-core = "1.18.0"
android-lifecycle-runtime = "2.10.0"

compose-bom = "2026.06.01"
compose-activity = "1.12.0"

test-espresso-core = "3.6.1"
test-junit = "4.13.1"
android-test-junit = "1.2.0"

[plugins]
android-application = { id = "com.android.application", version.ref = "agp" }
kotlin-compose = { id = "org.jetbrains.kotlin.plugin.compose", version.ref = "kotlin" }

[libraries]
android-core = { group = "androidx.core", name = "core", version.ref = "android-core" }
android-lifecycle-runtime = { group = "androidx.lifecycle", name = "lifecycle-runtime", version.ref = "android-lifecycle-runtime" }

compose-bom = { group = "androidx.compose", name = "compose-bom", version.ref = "compose-bom" }
compose-activity = { group = "androidx.activity", name = "activity-compose", version.ref = "compose-activity" }
compose-material3 = { group = "androidx.compose.material3", name = "material3" }
compose-icons-core = { group = "androidx.compose.material", name = "material-icons-core" }
compose-icons-extended = { group = "androidx.compose.material", name = "material-icons-extended" }
compose-ui = { group = "androidx.compose.ui", name = "ui" }
compose-ui-graphics = { group = "androidx.compose.ui", name = "ui-graphics" }
compose-ui-tooling = { group = "androidx.compose.ui", name = "ui-tooling" }
compose-ui-tooling-preview = { group = "androidx.compose.ui", name = "ui-tooling-preview" }

android-test-junit = { group = "androidx.test.ext", name = "junit", version.ref = "android-test-junit" }
test-compose-ui-junit4 = { group = "androidx.compose.ui", name = "ui-test-junit4" }
test-compose-ui-manifest = { group = "androidx.compose.ui", name = "ui-test-manifest" }
test-espresso-core = { group = "androidx.test.espresso", name = "espresso-core", version.ref = "test-espresso-core" }
test-junit = { group = "junit", name = "junit", version.ref = "test-junit" }

[bundles]
compose = [
    "compose-activity",
    "compose-material3",
    "compose-icons-core",
    "compose-icons-extended",
    "compose-ui",
    "compose-ui-graphics",
    "compose-ui-tooling",
    "compose-ui-tooling-preview",
]
